# coding: utf-8

"""
    Skill Repository

    The API description of the Skill Repository.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.learning_path_api import LearningPathApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLearningPathApi(unittest.TestCase):
    """LearningPathApi unit test stubs"""

    def setUp(self):
        self.api = LearningPathApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_learning_path_mgmt_controller_create_empty_learning_path(self):
        """Test case for learning_path_mgmt_controller_create_empty_learning_path

        """
        pass

    def test_learning_path_mgmt_controller_delete_learning_path(self):
        """Test case for learning_path_mgmt_controller_delete_learning_path

        """
        pass

    def test_learning_path_mgmt_controller_get_learning_path(self):
        """Test case for learning_path_mgmt_controller_get_learning_path

        """
        pass

    def test_learning_path_mgmt_controller_get_learning_paths_of_owner(self):
        """Test case for learning_path_mgmt_controller_get_learning_paths_of_owner

        """
        pass

    def test_learning_path_mgmt_controller_update_learning_path(self):
        """Test case for learning_path_mgmt_controller_update_learning_path

        """
        pass

    def test_learning_path_mgmt_controller_validate_learning_path(self):
        """Test case for learning_path_mgmt_controller_validate_learning_path

        """
        pass


if __name__ == '__main__':
    unittest.main()
