# coding: utf-8

"""
    Skill Repository

    The API description of the Skill Repository.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.career_profile_api import CareerProfileApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCareerProfileApi(unittest.TestCase):
    """CareerProfileApi unit test stubs"""

    def setUp(self):
        self.api = CareerProfileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_career_profile_controller_add_job(self):
        """Test case for career_profile_controller_add_job

        """
        pass

    def test_career_profile_controller_add_qualification_to_career_profile(self):
        """Test case for career_profile_controller_add_qualification_to_career_profile

        """
        pass

    def test_career_profile_controller_delete_job_history_at_career_profile_by_id(self):
        """Test case for career_profile_controller_delete_job_history_at_career_profile_by_id

        """
        pass

    def test_career_profile_controller_delete_qualification_to_career_profile(self):
        """Test case for career_profile_controller_delete_qualification_to_career_profile

        """
        pass

    def test_career_profile_controller_get_all_career_profiles(self):
        """Test case for career_profile_controller_get_all_career_profiles

        """
        pass

    def test_career_profile_controller_get_career_profile_by_id(self):
        """Test case for career_profile_controller_get_career_profile_by_id

        """
        pass

    def test_career_profile_controller_patch_career_profile_by_id(self):
        """Test case for career_profile_controller_patch_career_profile_by_id

        """
        pass

    def test_career_profile_controller_patch_job_history_at_career_profile_by_id(self):
        """Test case for career_profile_controller_patch_job_history_at_career_profile_by_id

        """
        pass

    def test_career_profile_controller_patch_qualification_to_career_profile(self):
        """Test case for career_profile_controller_patch_qualification_to_career_profile

        """
        pass


if __name__ == '__main__':
    unittest.main()
