# coding: utf-8

"""
    Skill Repository

    The API description of the Skill Repository.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.path_request_dto import PathRequestDto  # noqa: E501
from swagger_client.rest import ApiException


class TestPathRequestDto(unittest.TestCase):
    """PathRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPathRequestDto(self):
        """Test PathRequestDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.path_request_dto.PathRequestDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
