# coding: utf-8

"""
    Skill Repository

    The API description of the Skill Repository.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.path_finder_api import PathFinderApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPathFinderApi(unittest.TestCase):
    """PathFinderApi unit test stubs"""

    def setUp(self):
        self.api = PathFinderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_path_finder_controller_compute_path(self):
        """Test case for path_finder_controller_compute_path

        """
        pass

    def test_path_finder_controller_enrollment(self):
        """Test case for path_finder_controller_enrollment

        """
        pass

    def test_path_finder_controller_enrollment_by_goal(self):
        """Test case for path_finder_controller_enrollment_by_goal

        """
        pass

    def test_path_finder_controller_simulate_enrollment(self):
        """Test case for path_finder_controller_simulate_enrollment

        """
        pass

    def test_path_finder_controller_simulate_enrollment_by_goal(self):
        """Test case for path_finder_controller_simulate_enrollment_by_goal

        """
        pass

    def test_path_finder_controller_skill_analysis(self):
        """Test case for path_finder_controller_skill_analysis

        """
        pass

    def test_path_finder_controller_store_personalized_path(self):
        """Test case for path_finder_controller_store_personalized_path

        Experimental (WIP)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
