# coding: utf-8

"""
    Skill Repository

    The API description of the Skill Repository.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.learning_units_api import LearningUnitsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLearningUnitsApi(unittest.TestCase):
    """LearningUnitsApi unit test stubs"""

    def setUp(self):
        self.api = LearningUnitsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search_learning_unit_controller_add_learning_unit_search(self):
        """Test case for search_learning_unit_controller_add_learning_unit_search

        """
        pass

    def test_search_learning_unit_controller_check_learning_unit(self):
        """Test case for search_learning_unit_controller_check_learning_unit

        """
        pass

    def test_search_learning_unit_controller_delete_learning_unit(self):
        """Test case for search_learning_unit_controller_delete_learning_unit

        """
        pass

    def test_search_learning_unit_controller_get_learning_unit(self):
        """Test case for search_learning_unit_controller_get_learning_unit

        """
        pass

    def test_search_learning_unit_controller_get_learning_unit_search_with_filter(self):
        """Test case for search_learning_unit_controller_get_learning_unit_search_with_filter

        """
        pass

    def test_search_learning_unit_controller_list_learning_units(self):
        """Test case for search_learning_unit_controller_list_learning_units

        """
        pass

    def test_search_learning_unit_controller_patch_learning_unit(self):
        """Test case for search_learning_unit_controller_patch_learning_unit

        """
        pass


if __name__ == '__main__':
    unittest.main()
