# coding: utf-8

"""
    Skill Repository

    The API description of the Skill Repository.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.feedback_api import FeedbackApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFeedbackApi(unittest.TestCase):
    """FeedbackApi unit test stubs"""

    def setUp(self):
        self.api = FeedbackApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_feedback_controller_add_feedback(self):
        """Test case for feedback_controller_add_feedback

        """
        pass

    def test_feedback_controller_delete_feedback(self):
        """Test case for feedback_controller_delete_feedback

        """
        pass

    def test_feedback_controller_get_feedback(self):
        """Test case for feedback_controller_get_feedback

        """
        pass

    def test_feedback_controller_list_feedback(self):
        """Test case for feedback_controller_list_feedback

        """
        pass


if __name__ == '__main__':
    unittest.main()
