# coding: utf-8

"""
    Skill Repository

    The API description of the Skill Repository.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.berufe_net_api import BerufeNetApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBerufeNetApi(unittest.TestCase):
    """BerufeNetApi unit test stubs"""

    def setUp(self):
        self.api = BerufeNetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_berufe_net_controller_get_all_jobs(self):
        """Test case for berufe_net_controller_get_all_jobs

        """
        pass

    def test_berufe_net_controller_get_all_jobs_start_with(self):
        """Test case for berufe_net_controller_get_all_jobs_start_with

        """
        pass

    def test_berufe_net_controller_get_competencies_by_job_id(self):
        """Test case for berufe_net_controller_get_competencies_by_job_id

        """
        pass

    def test_berufe_net_controller_get_digital_competencies_by_job_id(self):
        """Test case for berufe_net_controller_get_digital_competencies_by_job_id

        """
        pass

    def test_berufe_net_controller_get_jobs_by_id(self):
        """Test case for berufe_net_controller_get_jobs_by_id

        """
        pass

    def test_berufe_net_controller_get_jobs_by_search_string(self):
        """Test case for berufe_net_controller_get_jobs_by_search_string

        """
        pass


if __name__ == '__main__':
    unittest.main()
