# coding: utf-8

"""
    Skill Repository

    The API description of the Skill Repository.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.learning_history_api import LearningHistoryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLearningHistoryApi(unittest.TestCase):
    """LearningHistoryApi unit test stubs"""

    def setUp(self):
        self.api = LearningHistoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_learning_history_controller_get_learned_skills(self):
        """Test case for learning_history_controller_get_learned_skills

        """
        pass

    def test_learning_history_controller_get_personalized_path(self):
        """Test case for learning_history_controller_get_personalized_path

        """
        pass

    def test_learning_history_controller_get_personalized_paths(self):
        """Test case for learning_history_controller_get_personalized_paths

        """
        pass


if __name__ == '__main__':
    unittest.main()
