# coding: utf-8

"""
    Skill Repository

    The API description of the Skill Repository.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.path_dto import PathDto  # noqa: E501
from swagger_client.rest import ApiException


class TestPathDto(unittest.TestCase):
    """PathDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPathDto(self):
        """Test PathDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.path_dto.PathDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
