# coding: utf-8

"""
    Skill Repository

    The API description of the Skill Repository.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.learning_profiles_api import LearningProfilesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLearningProfilesApi(unittest.TestCase):
    """LearningProfilesApi unit test stubs"""

    def setUp(self):
        self.api = LearningProfilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_learning_profile_controller_get_learning_profile_by_id(self):
        """Test case for learning_profile_controller_get_learning_profile_by_id

        """
        pass

    def test_learning_profile_controller_patch_learning_profile_by_id(self):
        """Test case for learning_profile_controller_patch_learning_profile_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
