# coding: utf-8

"""
    Skill Repository

    The API description of the Skill Repository.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.skill_api import SkillApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSkillApi(unittest.TestCase):
    """SkillApi unit test stubs"""

    def setUp(self):
        self.api = SkillApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_skill_mgmt_controller_adapt_repo(self):
        """Test case for skill_mgmt_controller_adapt_repo

        """
        pass

    def test_skill_mgmt_controller_add_skill(self):
        """Test case for skill_mgmt_controller_add_skill

        """
        pass

    def test_skill_mgmt_controller_create_repository(self):
        """Test case for skill_mgmt_controller_create_repository

        """
        pass

    def test_skill_mgmt_controller_delete_repo(self):
        """Test case for skill_mgmt_controller_delete_repo

        """
        pass

    def test_skill_mgmt_controller_delete_skill_with_check(self):
        """Test case for skill_mgmt_controller_delete_skill_with_check

        """
        pass

    def test_skill_mgmt_controller_delete_skill_without_check(self):
        """Test case for skill_mgmt_controller_delete_skill_without_check

        """
        pass

    def test_skill_mgmt_controller_find_skills(self):
        """Test case for skill_mgmt_controller_find_skills

        """
        pass

    def test_skill_mgmt_controller_find_skills_resolved(self):
        """Test case for skill_mgmt_controller_find_skills_resolved

        """
        pass

    def test_skill_mgmt_controller_get_all_skills(self):
        """Test case for skill_mgmt_controller_get_all_skills

        """
        pass

    def test_skill_mgmt_controller_get_resolved_skill(self):
        """Test case for skill_mgmt_controller_get_resolved_skill

        """
        pass

    def test_skill_mgmt_controller_get_skill(self):
        """Test case for skill_mgmt_controller_get_skill

        """
        pass

    def test_skill_mgmt_controller_list_repositories(self):
        """Test case for skill_mgmt_controller_list_repositories

        """
        pass

    def test_skill_mgmt_controller_load_repository(self):
        """Test case for skill_mgmt_controller_load_repository

        """
        pass

    def test_skill_mgmt_controller_search_for_repositories(self):
        """Test case for skill_mgmt_controller_search_for_repositories

        """
        pass

    def test_skill_mgmt_controller_update_skill(self):
        """Test case for skill_mgmt_controller_update_skill

        """
        pass


if __name__ == '__main__':
    unittest.main()
